JuliaReach/Reachability.jl

REQUIRE
src/Benchmarks/Benchmarks.jl
src/Reachability.jl
src/Utils/Utils.jl
src/logging.jl
src/options.jl
src/solve.jl

logger support (see #7)

---

docs/make.jl
docs/src/index.md
docs/src/lib/interface.md
docs/src/lib/systems.md
src/Properties/check_explicit_block.jl
src/Properties/check_explicit_blocks.jl
src/ReachSets/discretize.jl
src/ReachSets/reach_explicit_block.jl
src/ReachSets/reach_explicit_blocks.jl
src/Systems/Systems.jl
src/Utils/Utils.jl
src/solve.jl
test/ReachSets/unit_discretization.jl
test/Systems/unit_NonDeterministicInput.jl
test/Systems/unit_System.jl

I changed a bit the documentation of `Systems.jl`.
The only code change are
- I turned some inner constructors to outer constructors.
- I reordered the fields of `DiscreteSystem`.
- I changed the field name of `InputState` from `sf` to `set`. (This implied a lot of changes in other files.)

Systems: documentation and minor changes

---

src/Properties/check_property.jl
src/solve.jl
test/Reachability/unit_solve.jl

#38 - fix property checking

---

docs/make.jl
docs/src/index.md
docs/src/lib/transformations.md
src/Reachability.jl
src/Transformations/Transformations.jl
src/solve.jl

- overhaul of `Transformations.jl`, most notably:
* also support `ContinuousSystem`s
* change argument order
- added documentation

revise Transformations

---

README.md
codecov.yml

@mforets: [In LazySets](https://github.com/JuliaReach/LazySets.jl/blob/master/codecov.yml) the file contains a token. Is this helpful? If yes, where did you get it?

reactivate codecov

---

src/Properties/IntersectionProperty.jl
src/Properties/LinearConstraintProperty.jl
src/Properties/Properties.jl
src/Properties/Property.jl
src/Properties/SubsetProperty.jl
src/Reachability.jl
test/Properties/unit_Property.jl
test/Reachability/unit_solve.jl

See #35.
The build errors stem from LazySets.jl.

#35 - Generalized properties

---

src/Properties/IntersectionProperty.jl
src/Properties/LinearConstraintProperty.jl
src/Properties/Properties.jl
src/Properties/Property.jl
src/Properties/SubsetProperty.jl
src/Properties/check_explicit_block.jl
src/Properties/check_explicit_blocks.jl
src/Properties/check_property.jl
src/ReachSets/project_reach.jl
src/ReachSets/reach.jl
src/ReachSets/reach_explicit_block.jl
src/ReachSets/reach_explicit_blocks.jl
src/Reachability.jl
src/Utils/Utils.jl
src/options.jl
src/solve.jl
test/Properties/unit_Property.jl
test/Reachability/unit_solve.jl

See #24.
This branch is based on #40.
Missing: plot recipes for general arrays.
@mforets: I probably need your help for that.

Type parameter for reach set representation

---

src/Properties/check_explicit_block.jl
src/Properties/check_explicit_blocks.jl

#58 - Generalize numeric type in `check` mode

---

src/ReachSets/project_reach.jl

#60 - Fix project_reach

---

src/ReachSets/project_reach.jl
src/solve.jl

#64 - make project_reach respect set_type

---

src/ReachSets/discretize.jl
src/ReachSets/reach.jl
src/options.jl
src/solve.jl

Closes #52.
this is a WIP that has in it the option passed to `discretize`, but needs to add `lazy_sih` as a valid option for the interface.

#52 - Use lazy SymmetricIntervalHull

---

test/ReachSets/unit_discretization.jl
test/Reachability/unit_solve.jl

For the moment these additions only check that some options execute.
We could think about adding some `@test` for some options.

[WIP] Test reach options

---

src/options.jl
src/solve.jl

Closes #37 (after outsourcing one of the tasks which is complicated).

#37 - fix some options (verbosity + docs)

---

test/Reachability/unit_solve.jl

#81 - Property failure for a random matrix in unit tests

---

src/plot_recipes.jl

Fix plotting for non-polygons

---

src/Properties/Properties.jl
src/Properties/tune.jl
src/Reachability.jl
test/Properties/alltests.jl
test/Properties/unit_tune.jl

Refactor tune_delta, update docstring and unit test

---

src/plot_recipes.jl

this fixes the signature and error message for non-projected reach sets.

fix cartesian product plot_sol signature

---

src/Properties/check_property.jl
src/ReachSets/reach.jl
src/solve.jl

Closes #94.
I did not add a `preprocess` function because it was a one-liner.

#94 - Inconsistent behavior for assume_sparse mode

---

src/Properties/check_explicit_blocks.jl
src/ReachSets/reach_explicit_blocks.jl

#96 - Lazy mexp version assigns immutable field

---

src/solve.jl

#101 - fix assume_sparse

---

src/plot_recipes.jl

#105 - Always use convex_hull

---

src/options.jl

#109 - Fix project_reach for Interval set_type

---

src/Properties/check_blocks.jl
src/Properties/check_property.jl
src/ReachSets/reach.jl
src/ReachSets/reach_blocks.jl
src/Utils/Utils.jl

#111 - Fix slowdowns with sparse models and 1D blocks

---

src/Properties/check_blocks.jl
src/ReachSets/reach_blocks.jl

fix variable name bug

---

src/Properties/check_blocks.jl
src/ReachSets/reach_blocks.jl
test/Reachability/unit_solve.jl

#130 - Fix LinearMap with RowVector

---

src/ReachSets/discretize.jl

#147 - Convert to sparse matrix in discretization with lazy_expm

---

src/options.jl
test/Reachability/unit_solve.jl

#150 - Default partition

---

src/options.jl

use ':lazy_sih = false' by default

---

src/Properties/tune.jl

Changes:
* simplified code
* more parameters to tune
* rounding to given precision

revised tune_delta

---

src/logging.jl
src/options.jl

#156 - Option to write all logger output to a file

---

src/options.jl
test/Reachability/unit_options.jl

#158 - Do not modify input options

---

src/Properties/check_blocks.jl
src/Properties/check_property.jl
src/ReachSets/reach.jl
src/ReachSets/reach_blocks.jl
test/Reachability/unit_solve.jl

#89 - Make lazy_expm analysis consistent wrt sparse/dense

---

src/Properties/check_blocks.jl
src/Properties/check_property.jl
src/options.jl
src/solve.jl

#167 - Option to deactivate eager termination of property checking

---

src/Properties/Properties.jl
src/Properties/check_blocks.jl

#124 - Rename check_blocks! to check_blocks

---

src/Properties/check_blocks.jl
src/Properties/check_property.jl
src/ReachSets/reach.jl
src/ReachSets/reach_blocks.jl
src/options.jl
src/solve.jl

#169 - Add option to keep inputs a lazy set

---

src/Properties/check_property.jl
src/ReachSets/reach.jl

#170 - Skip decomposition for one-block-partitions

---

src/Properties/check_blocks.jl
src/Properties/check_property.jl

#176 - Remove overapproximate function from property checking

---

src/solve.jl

#183 - Crash for system without inputs

---

src/Utils/Utils.jl
test/Reachability/unit_solve.jl

#187 - Do not mix Int and vector indexing in partition

---

src/Properties/check_property.jl
src/ReachSets/reach.jl
src/options.jl
src/solve.jl

#194 - Add option to use template directions for overapproximation

---

src/Properties/check_property.jl
src/ReachSets/reach.jl
src/options.jl

#198 - Use CacheMinkowskiSum with :lazy_inputs_interval option

---

src/options.jl
src/solve.jl

#206 - Add option to convert SparseMatrixExp to explicit matrix

---

src/options.jl

#220 - Change default value of :apply_projection

---

src/options.jl
src/solve.jl
test/Reachability/unit_solve.jl

#220 - Change default value of and rename :apply_projection

---

src/ReachSets/project_reach.jl
src/solve.jl

#42 - Revise project_reach.jl

---

src/ReachSets/project_reach.jl

#258 - Plotting vs. time

---

src/ReachSets/DiscretePost/TextbookDiscretePost.jl
src/options.jl
src/solve.jl

#280 - Option to deactivate fixpoint check

---

src/ReachSets/DiscretePost/TextbookDiscretePost.jl
test/Reachability/unit_solve_hybrid_thermostat.jl

#279 - Transitions of hybrid systems are not handled correctly

---

src/ReachSets/DiscretePost/TextbookDiscretePost.jl

extended d_post to use HPolytope invariant

---

src/ReachSets/DiscretePost/DiscretePost.jl
src/ReachSets/DiscretePost/LazyTextbookDiscretePost.jl
src/ReachSets/DiscretePost/TextbookDiscretePost.jl
src/ReachSets/ReachSets.jl
test/REQUIRE
test/Reachability/unit_solve_hybrid.jl
test/Reachability/unit_solve_hybrid_bouncing_ball.jl

#272 - Lazy discrete post operator

---

src/ReachSets/project_reach.jl

projection fix

---

src/ReachSets/DiscretePost/LazyTextbookDiscretePost.jl
src/ReachSets/DiscretePost/TextbookDiscretePost.jl
src/options.jl
src/solve.jl
test/Reachability/unit_solve_hybrid_bouncing_ball.jl

Add map of (initial_loc, initial_set)

---

src/ReachSets/DiscretePost/TextbookDiscretePost.jl

#297 - Use H-representation, instead of V-representation in TextbookDiscretePost

---

src/ReachSets/reach.jl

#302 - Fix shortcut for N=1

---

src/ReachSets/DiscretePost/DiscretePost.jl
src/ReachSets/DiscretePost/LazyTextbookDiscretePost.jl
src/ReachSets/DiscretePost/TextbookDiscretePost.jl
src/options.jl
src/solve.jl

#301 - Clustering interface and default implementation

---

src/solve.jl

#300 - Replace HPolytope by HPolyhedron

---

src/solve.jl

#306 - Add initial approximation(s) to passed_list

---

REQUIRE
src/ReachSets/DiscretePost/DiscretePost.jl
src/ReachSets/DiscretePost/LazyTextbookDiscretePost.jl
src/Reachability.jl
src/solve.jl

#319 - Depth limit for line search

---

src/ReachSets/DiscretePost/ApproximatingDiscretePost.jl
src/ReachSets/DiscretePost/DiscretePost.jl
src/ReachSets/DiscretePost/LazyTextbookDiscretePost.jl

#322 - Make :overapproximation option for LazyTextbookDiscretePost controllable

---

src/ReachSets/DiscretePost/ApproximatingDiscretePost.jl
src/ReachSets/DiscretePost/DiscretePost.jl
src/ReachSets/DiscretePost/LazyTextbookDiscretePost.jl
src/ReachSets/DiscretePost/TextbookDiscretePost.jl
src/options.jl
src/solve.jl

#324 - Refactor fixpoint check to apply before clustering

---

src/ReachSets/DiscretePost/ApproximatingDiscretePost.jl
src/ReachSets/DiscretePost/DiscretePost.jl
src/ReachSets/DiscretePost/LazyTextbookDiscretePost.jl
src/ReachSets/DiscretePost/TextbookDiscretePost.jl

Closes #333.
Closes #324.
Closes #328.

#333 - Function tube⋂inv! returns wrong variable

---

src/ReachSets/DiscretePost/DiscretePost.jl
src/solve.jl

Performance fixes for subset check (use Hyperrectangles by default)

---

src/ReachSets/DiscretePost/ApproximatingDiscretePost.jl
src/ReachSets/DiscretePost/DiscretePost.jl
src/ReachSets/DiscretePost/LazyTextbookDiscretePost.jl

#342 - Default dirs in ApproximatingDiscretePost

---

src/ReachSets/DiscretePost/LazyTextbookDiscretePost.jl
src/ReachSets/DiscretePost/TextbookDiscretePost.jl
src/ReachSets/ReachSets.jl

#344 - Controlling lazyiness in hybrid algos

---

src/ReachSets/DiscretePost/ApproximatingDiscretePost.jl
src/ReachSets/DiscretePost/LazyTextbookDiscretePost.jl

some fixes of #344 : the order in which operations where taken was not optimal.

fixes in LazyTextbookDiscretePost

---

src/ReachSets/ContinuousPost/BFFPSV18.jl
src/ReachSets/DiscretePost/ApproximatingDiscretePost.jl
src/ReachSets/DiscretePost/LazyTextbookDiscretePost.jl
src/ReachSets/DiscretePost/TextbookDiscretePost.jl
src/ReachSets/reach.jl
src/ReachSets/reach_blocks.jl
src/ReachSets/reach_blocks_wrapping_effect.jl
src/solve.jl
test/Reachability/unit_solve_hybrid_bouncing_ball.jl
test/Reachability/unit_solve_hybrid_thermostat.jl

#250 - Generalize termination criterion for continuous-time reachability algorithm

---

src/options.jl
src/solve.jl

Update usage of Options

---

src/ReachSets/ContinuousPost/BFFPSV18.jl
src/ReachSets/Properties/LinearConstraintProperty.jl
src/ReachSets/Properties/check_blocks.jl
src/ReachSets/discretize.jl
src/ReachSets/inout_map_reach.jl
src/ReachSets/reach.jl
src/ReachSets/reach_blocks.jl
src/ReachSets/reach_blocks_wrapping_effect.jl
src/Utils/Utils.jl

[WIP] 0.7 updates

---

src/ReachSets/Properties/tune.jl
src/ReachSets/ReachSets.jl
src/Utils/Utils.jl
test/Properties/unit_tune.jl
test/ReachSets/unit_discretization.jl
test/Systems/unit_NonDeterministicInput.jl
test/Systems/unit_System.jl

Fix deprecation warnings in unit tests

---

src/options.jl

#382 - Options merge! does not work in place

---

src/ReachSets/ContinuousPost/BFFPSV18.jl
src/ReachSets/ReachSets.jl
test/Reachability/solve_continuous.jl

- add inner constructor for BFFPSV18
- uniformize notation in BFFPSV18

notation and inner constructor for BFFPSV18

---

src/Utils/Utils.jl

#414 - Make relpath work in 0.7

---

docs/make.jl
docs/src/citations.md

#427 - Add citations page

---

src/ReachSets/DiscretePost/DiscretePost.jl

#441 - Support for reset assignments

---

src/Options/dictionary.jl

#255 - Add TwoLayerDictionary

---

src/Options/dictionary.jl

#255 - Add OptionSpec

---

docs/make.jl
docs/src/index.md
docs/src/lib/algorithms.md
src/Options/dictionary.jl
src/ReachSets/ContinuousPost/BFFPSV18/BFFPSV18.jl
src/ReachSets/ReachSets.jl

#255 - Add options functionality

---

src/Options/default_options.jl

Generalization of input type for #480.

Allow for more general dictionary

---

src/ReachSets/DiscretePost/LazyDiscretePost.jl

#488 - Generalize combination of invariant and guard in LazyDiscretePost

---

src/ReachSets/ContinuousPost/BFFPSV18/reach.jl

Fix argument count in propagations

---

docs/src/lib/properties.md
src/Properties/BadStatesProperty.jl
src/Properties/Conjunction.jl
src/Properties/Disjunction.jl
src/Properties/Properties.jl
src/Properties/Property.jl
src/Properties/SafeStatesProperty.jl
test/Properties/unit_Property.jl

#522 - Add getter function for dimension to properties

---

src/ReachSets/ContinuousPost/BFFPSV18/check_property.jl
src/ReachSets/ContinuousPost/BFFPSV18/reach.jl

#490 - Decomposition of one-block partitions

---

test/Reachability/models/bouncing_ball.jl
test/Reachability/models/thermostat.jl

#348 - Misuse of ConstrainedLinearControlXSystems

---

.travis.yml
REQUIRE

- use new tagged version of TaylorSeries as a lower bound in REQUIRE
- remove pulling from `TaylorSeries#master` in travis

Update TaylorSeries version

---

src/ReachSets/ContinuousPost/BFFPSV18/BFFPSV18.jl
src/ReachSets/ContinuousPost/BFFPSV18/check_property.jl
src/ReachSets/ContinuousPost/BFFPSV18/reach.jl
src/Utils/Utils.jl

#571 - Revise matrix_conversion

---

src/ReachSets/ContinuousPost/GLGM06/project.jl

#584 - Fix GLGM06 projection

---

src/ReachSets/ContinuousPost/GLGM06/project.jl

Remove redundant method

---

src/Utils/systems.jl

#589 - Fix abbreviation of BB system type

---

.travis.yml
REQUIRE

EDIT:
Some relevant links:
- https://gist.github.com/jamesarosen/e29076bd81a099f0f72e
- https://github.com/phpbb/phpbb/blob/3.1.x/.travis.yml
- https://github.com/pantheon-deprecated/travis-scripts/blob/master/examples/example.travis.yml

Update Travis CI script

---

src/ReachSets/DiscretePost/DiscretePost.jl

Related to https://github.com/JuliaReach/Reachability.jl/issues/628.

Add template dirs for discrete post

---

src/ReachSets/discretize.jl

#643 - Use operator norm

---

.travis.yml

Fix Codecov

---

.travis.yml
docs/Project.toml
docs/make.jl
docs/src/lib/discretize.md
docs/src/lib/transformations.md
src/Options/dictionary.jl
src/ReachSets/discretize.jl
src/Reachability.jl
src/Utils/systems.jl

This also fixes a warning via `import LazySets: LinearMap, AffineMap, ResetMap`.

Build docs in Travis again

---

.travis.yml

Apparently I broke the build matrix in #663. My workaround is to build the docs not with a stage but just with another command.
`coverage: true` did not work here, so I kept the explicit Julia command.

Fix Travis build matrix and coverage

---

.travis.yml
Project.toml

I also upgraded the development-version test suite to v1.2.

Update tests for Julia v1.2

---

src/ReachSets/ContinuousPost/TMJets/reach.jl

#700 - Change info to warning in TMJets max steps

---

src/ReachSets/ContinuousPost/TMJets/project.jl
src/solve.jl

#702 - MethodError in TMJets projection

---

src/ReachSets/ContinuousPost/TMJets/init.jl
src/ReachSets/ContinuousPost/TMJets/post.jl
test/Reachability/solve_continuous.jl

#635 - Add output set type option to TMJets

---

src/plot_recipes.jl

This fixes the "default" plotting labels.

Let subindices be false by default

---

test/Reachability/solve_continuous.jl

#242 - Add example for issue 242

---

src/solve.jl
test/Reachability/solve_continuous.jl

#699 - Add dimensional check in solve!

---

src/ReachSets/ContinuousPost/BFFPSV18/reach.jl

Fix bug for N == 1 in BFFPSV18

---

src/ReachSets/discretize.jl

Closes #730.
Further simplifications:
* creation of identity interval matrix
* outsourcing of common error code

#730 - Combine linear maps in interval-matrix discretization

---

src/ReachSets/ContinuousPost/ASB07_decomposed/options.jl

This requires ~~https://github.com/JuliaReach/LazySets.jl/pull/1920.~~

Use zonotope decomposition in ASB07_decomposed

---

src/ReachSets/ContinuousPost/GLGM06/reach.jl

see: https://github.com/JuliaReach/Reachability.jl/issues/680

Update GLGM06 for the homogeneous case
