JuliaReach/Reachability.jl

src/Utils/Utils.jl
I revisited `Utils.jl`, mainly for documentation overhaul.
Should we adapt `plot_sparsity` to the new `Plots` package (not necessarily in the near future, but create an issue)? Currently it uses `PyPlot`.
I also do not understand how I can resolve the `Documenter` warnings in this file.
All the functions are documented already!?
=> polished Utils.jl

docs/src/lib/systems.md, src/Systems/Systems.jl, test/Systems/unit_NonDeterministicInput.jl
- revised documentation for `Systems` according to new standards
- removed constructor for empty `ConstantNonDeterministicInput`
=> documentation Systems

docs/src/lib/systems.md, src/Properties/check_explicit_block.jl, src/Properties/check_explicit_blocks.jl, src/ReachSets/discretize.jl, src/ReachSets/reach_explicit_block.jl, src/ReachSets/reach_explicit_blocks.jl, src/Systems/Systems.jl, src/Utils/Utils.jl, test/ReachSets/unit_discretization.jl, test/Systems/unit_NonDeterministicInput.jl, test/Systems/unit_System.jl
@mforets: Can you have a look what I did here?
I destroyed the iterator structure.
Now I realized that having this was not so bad :/
This change was independent of my original change, so I can get it back - should I?
After all, I do not think anymore that this change was necessary, so we can also just forget about it.
Furthermore, I find it quite inconsistent that the iteration over a `ConstantNonDeterministicInput` is endless and the iteration over a `TimeVaryingNonDeterministicInput` is finite.
I copied this behavior, but I do not like it.
I see that it has an application (namely you can iterate independent of the type and it just works), but still...
=> #21 - changed InputState

src/Properties/check_explicit_block.jl, src/Properties/check_explicit_blocks.jl, src/ReachSets/discretize.jl, src/ReachSets/project_reach.jl, src/ReachSets/reach_explicit_block.jl, src/ReachSets/reach_explicit_blocks.jl, src/Systems/Systems.jl, src/Utils/Utils.jl, test/ReachSets/unit_discretization.jl, test/Systems/unit_System.jl
I replaced all `VoidSet`s by `ZeroSet`s. This is not totally correct inside the `reach*`/`check*` functions because now for empty matrix block rows we return the zero set. But maybe this is a corner case that does not make sense anyway...
@mforets: [This line](https://github.com/JuliaReach/Reachability.jl/blob/master/src/ReachSets/project_reach.jl#L81) is making trouble in the new version. The reason is that previously we did not overload `*` for `CartesianProductArray` and hence a new `CartesianProduct` object was created (not nice, but it worked). Now we try to add the `BallInf` to the array, but it has type `HPolygon[]`, so we get a type error.
I see the following ways to solve:
* Make the `BallInf` here an `HPolygon`.
Cons: counters the plan to generalize the types (#24); not that …
=> [WIP] adapt to LazySets changes

REQUIRE, src/Properties/Properties.jl, src/Properties/check_blocks.jl, src/ReachSets/ReachSets.jl, src/ReachSets/reach_blocks.jl
=> [WIP #113] Use a progress bar

src/Properties/check_blocks.jl, src/Properties/check_property.jl, src/ReachSets/reach.jl, src/ReachSets/reach_blocks.jl
See #75.
Merges the analysis modes "with inputs" and "without inputs".
The git merge looks ugly, but there were only a few actual changes, namely wrapping the code for "with inputs" in an `if` block.
An inspection with `@code_warntype` shows that the generated code just omits these blocks if there are no inputs, so the performance is the same as before.
=> [WIP #75] Merge w/ and w/o inputs

src/Properties/check_blocks.jl, src/ReachSets/reach_blocks.jl
=> #125 - Fix get_rows for 1D block

src/logging.jl
Closes #190.
(Only merge this when `Memento` has made a new release. The current version, where this fix is not needed and actually crashes, is v0.6.0.)
=> #190 - Fix deprecation warning in Memento

src/Properties/check_blocks.jl
Small bugfix in a rare case (`N == 1`, lazy violation detection, only a violation at index 1).
=> Fix lazy violation detection at index 1 with N=1

src/Properties/check_property.jl, src/ReachSets/reach.jl, src/Utils/Utils.jl
Closes #91.
This is an alternative solution to #112. In this minimally invasive approach here we do the projection but keep it lazy, in #112 the whole set is kept lazy (not even projection).
Closes #112.
=> #91 - Fix lazy_X0 option

src/Properties/check_property.jl, src/ReachSets/reach.jl
Adapts this package to the change coming in [`LazySets.jl`'s #472](https://github.com/JuliaReach/LazySets.jl/pull/472).
=> Adapt to type parameter change in LinearMap

test/Reachability/unit_solve_hybrid_bouncing_ball.jl, test/Reachability/unit_solve_hybrid_thermostat.jl
Closes #313.
The models will work after merging open PRs in `LazySets`.
EDIT: Apparently this is not true anymore. We need to have https://github.com/JuliaReach/LazySets.jl/issues/798.
=> Replace unbounded `HPolytope`s by `HPolyhedron`

src/ReachSets/Properties/check_blocks.jl, src/ReachSets/reach_blocks.jl, src/Utils/Utils.jl
This also fixes a deprecation warning (see #361).
I first tried with `any(v->v!=0, x)`, but in `@time` this is expensive. Now that I implemented it, I also tried with `@btime`, and then suddently the `any` approach is efficient. I have no idea what is going on here. Should we keep the function nevertheless? It is a bit more readable and shorter to write. And we anyway want to replace `findfirst`.
```julia
julia> x = [zeros(Int, 10000); 1];
julia> @btime any(v->v!=0, x) # for some reason this is efficient
4.309 μs (0 allocations: 0 bytes)
true
julia> @time any(v->v!=0, x) # for some reason this is not efficient
0.008472 seconds (8.33 k allocations: 412.224 KiB)
true
julia> @btime findfirst(v->v!=0, x)
6.021 μs (1 allocation: 16 bytes)
10001
julia> @btime findfirst(x) # deprecated
74.652 μs …
```
=> Fast non-zero check for arrays

src/ReachSets/DiscretePost/ConcreteDiscretePost.jl, src/ReachSets/DiscretePost/LazyDiscretePost.jl, src/ReachSets/ReachSets.jl
- update ConcreteDiscretePost with a default inner constructor and `options` field
- use correct order for options in check_aliases_and_add_default_value (See #379)
=> updates discrete post

test/Reachability/solve_continuous.jl
This adds a test for an affine purely continuous ODE; in particular shows the usage of `ConstrainedLinearControlContinuousSystem` with an input `ConstantInput(B*U))`.
Compare to eg. [here](https://github.com/JuliaReach/Reachability.jl/blob/master/test/Reachability/solve_hybrid_bouncing_ball.jl#L17) and [here](https://github.com/JuliaReach/Reachability.jl/blob/master/test/Reachability/solve_hybrid_thermostat.jl#L22) where the usage is *incorrect*; the fact that they don't break is that in the processing we create a new system [here](https://github.com/JuliaReach/Reachability.jl/blob/master/src/solve.jl#L212), where `loc.U` is converted into a constant input.
=> Add test for affine ODE

.travis.yml, test/Reachability/solve_hybrid_bouncing_ball.jl, test/Reachability/solve_hybrid_thermostat.jl
Optim using is needed in the tests v0.7 
(this is a minimal change; we could otherwise run the `using Optim` inside the functions that need it inside Reachability, but then that's just about the same of adding this package as a requrement for LazySets, no?)
=> Optim import needed in v0.7

src/ReachSets/ContinuousPost/BFFPSV18.jl, src/ReachSets/Properties/check_property.jl, src/ReachSets/ReachSets.jl, src/ReachSets/reach.jl, src/Utils/Utils.jl, src/compat.jl, src/logging.jl, src/solve.jl
Closes #371.
Closes #408.
I am not too happy with the output format, but I find it acceptable:
```julia
elapsed time: 7.152557373046875e-6 seconds
```
But I did not find an easy way to control that.
There is [`@printf`](https://stackoverflow.com/questions/24580334/jula-repl-number-formatting#24593139), but this requires another (standard) package.
=> #371 - Deprecation warning with tic - tocc

src/logging.jl
This is related to #407.
Using `digits` argument:
```julia
julia> s = solve(InitialValueProblem(LinearContinuousSystem(A), X0), :T=>0.1, :verbosity=>1);
[info] Reachable States Computation...
[info] Time discretization...
[info] elapsed time: 0.0 seconds
[info] - Decomposing X0
[info] elapsed time: 0.0 seconds
[info] - Computing successors
[info] elapsed time: 0.0 seconds
[info] - Total
[info] elapsed time: 0.0 seconds
[info] Projection...
[info] elapsed time: 0.0 seconds
```
Using `sigdigits` argument:
```julia
julia> s = solve(InitialValueProblem(LinearContinuousSystem(A), X0), :T=>0.1, :verbosity=>1);
[info] Reachable States Computation...
[info] Time discretization...
[info] elapsed time: 0.000193 seconds
[info] - Decomposing X0
[info] elapsed time: 7.39e-5 seconds
[info] - Computing …
```
=> Use sigdigits in logging

src/solve.jl, test/Reachability/solve_hybrid_bouncing_ball.jl, test/Reachability/solve_hybrid_thermostat.jl
=> #397 - constrained_dimensions

src/Utils/Utils.jl, src/Utils/systems.jl, src/solve.jl
This branch:
- Adds docstrings to `default_operator` and `distribute_initial_set` (previously named `init_states_from_init_sys`)
- Moves `constrained_dimensions(HS::HybridSystem)` to `Utils` 
- Removes the tuple version of `default_operator` for hybrid systems.
=> Refactoring in solve.jl

.travis.yml
Reason: Currently the new releases of `MathematicalSystems` and `HybridSystems` are not found on `METADATA`. There are investigations, but the show must go on here.
=> Use dev version for MathematicalSystems & HybridSystems

src/ReachSets/DiscretePost/ConcreteDiscretePost.jl, src/ReachSets/DiscretePost/DiscretePost.jl, src/ReachSets/DiscretePost/LazyDiscretePost.jl, test/Reachability/models/bouncing_ball.jl, test/Reachability/models/thermostat.jl
=> #436 - Use AbstractMap interface in hybrid models

src/ReachSets/DiscretePost/LazyDiscretePost.jl
* move intersection to the correct place according to the name
* add a new option for intersection at the old place
* simplify code
=> Revise LazyDiscretePost

src/Options/default_options.jl, src/solve.jl
Closes #473.
This PR will also implement the poorman's version of #447: Just compute the (concrete) reachable states and check the property afterward.
=> #473 - Checking different safety properties in different locations

src/solve.jl
Closes #482.
There are also two bugfixes here. Property checking in the hybrid setting did not work at all :astonished:
1. The call to check a property has changed recently, but was not updated here.
2. Properties given as mappings "location index → property" were accessed with the location itself (instead of the index).
=> #482 - Support partial property mappings

docs/src/lib/discretize.md, src/ReachSets/ContinuousPost/BFFPSV18/BFFPSV18.jl, src/ReachSets/ContinuousPost/BFFPSV18/check_property.jl, src/ReachSets/ContinuousPost/BFFPSV18/reach.jl, src/ReachSets/discretize.jl, src/Reachability.jl, src/Transformations/Transformations.jl, src/Utils/Utils.jl, src/Utils/systems.jl, src/solve.jl, test/Properties/unit_tune.jl, test/ReachSets/unit_discretization.jl, test/Reachability/models/bouncing_ball.jl, test/Reachability/models/thermostat.jl, test/Reachability/solve_continuous.jl, test/Systems/unit_System.jl, test/runtests.jl
Closes https://github.com/JuliaReach/Reachability.jl/issues/465.
Closes https://github.com/JuliaReach/Reachability.jl/issues/252.
Closes https://github.com/JuliaReach/Reachability.jl/issues/193.
Closes https://github.com/JuliaReach/Reachability.jl/issues/491.
Closes https://github.com/JuliaReach/Reachability.jl/issues/117.
=> Revise discretize

src/ReachSets/ContinuousPost/BFFPSV18/BFFPSV18.jl, src/ReachSets/ContinuousPost/BFFPSV18/check_property.jl, src/ReachSets/ContinuousPost/BFFPSV18/reach.jl, src/ReachSets/DiscretePost/DiscretePost.jl, src/ReachSets/ReachSets.jl, src/Utils/Utils.jl, test/Reachability/solve_continuous.jl
=> #471 - Merge overapproximation options

src/Utils/Utils.jl, src/Utils/normalization.jl, src/Utils/systems.jl, src/solve.jl, test/Reachability/solve_continuous.jl
=> #520 - Accept lazyset for a constant input

src/ReachSets/discretize.jl, test/ReachSets/unit_discretization.jl
=> #512 - Add new option to discretize

src/ReachSets/ReachSets.jl, src/solve.jl
- `solve` copies the options,
https://github.com/JuliaReach/Reachability.jl/blob/1b41551b9f5d4e82e71519861fac50b480b6ed6b/src/solve.jl#L53
- `init` copies the options again, 
https://github.com/JuliaReach/Reachability.jl/blob/1b41551b9f5d4e82e71519861fac50b480b6ed6b/src/ReachSets/ContinuousPost/BFFPSV18/BFFPSV18.jl#L184
=> Call modifying init! in solve!

src/ReachSets/ContinuousPost/BFFPSV18/BFFPSV18.jl, test/Reachability/solve_continuous.jl
The current implementation crashes when trying to plot the result for a purely-continuous system. The problem was that we return a `TwoLayeredOptions` in the result, and that is not allowed in the plot recipe.
~I decided to wrap the resulting options in an `Options` structure again here.~
=> Let continuous post return input options

src/ReachSets/ContinuousPost/BFFPSV18/BFFPSV18.jl, src/ReachSets/ContinuousPost/BFFPSV18/reach.jl
Now one can do `:block_types_iter => nothing`.
=> Add no-overapproximation option

REQUIRE, docs/src/lib/systems.md, src/Utils/normalization.jl, src/solve.jl, test/Reachability/solve_continuous.jl
Closes #529.
Closes #527.
~~Requires https://github.com/JuliaReach/MathematicalSystems.jl/pull/85.~~ Available in version v0.6.3
=> Update transformation to canonical form

src/ReachSets/ContinuousPost/BFFPSV18/reach.jl
=> Fix for copy bug in 'no overapproximation' option

src/ReachSets/project_reach.jl
Fixes:
```julia
ERROR: LoadError: MethodError: no method matching DomainError()
Closest candidates are:
DomainError(::Any) at boot.jl:256
DomainError(::Any, ::Any) at boot.jl:257
```
=> Fix empty error message in projection

src/ReachSets/ContinuousPost/BFFPSV18/check_blocks.jl, src/ReachSets/ContinuousPost/BFFPSV18/check_property.jl, src/ReachSets/ContinuousPost/BFFPSV18/reach.jl, src/ReachSets/ContinuousPost/BFFPSV18/reach_blocks.jl, src/ReachSets/ReachSets.jl, src/solve.jl, test/Reachability/solve_continuous.jl
Closes #538.
The second commit is an unrelated bugfix.
=> #538 - Analysis with unbounded time

src/Utils/normalization.jl, src/Utils/systems.jl, src/solve.jl, test/Reachability/solve_continuous.jl
=> #559 - Accept CA_S in normalization

src/solve.jl
* Do not take the intersection with the source invariant if not needed.
* Do not convert `HalfSpace` invariants to `HPolyhedron`.
=> Revise initialization of hybrid-system analysis

src/solve.jl
For the purpose of running continuous post different than BFFPSV18, this just ensures that `inout_map` is used for the algorithm that needs it.
=> Use inout_map in solve for BFFPSV

src/ReachSets/DiscretePost/DiscretePost.jl, src/ReachSets/DiscretePost/LazyDiscretePost.jl, src/Utils/Utils.jl, test/Reachability/solve_continuous.jl
Closes #562.
Closes #628.
I decided to remove the overapproximation symbols because they complicate things considerably. We anyway never truly used them.
=> #562 - Revise overapproximation options with template directions

src/ReachSets/ContinuousPost/TMJets/reach.jl
Apart from small tweaks this branch updates wrt TaylorModels#master and the idea of returning the TMs in the solution (before box o.a.). Note, however, that in a follow-up PR we should fully "branch" it to the cont post perhaps adding a new option to choose the type of the solution. Note also that `ReachSolution` takes arguments of type `LazySet` but `TaylorModel` is not of that type (we could add this in the future..).
=> Update TMJets returning the TMs

src/ReachSets/ContinuousPost/BFFPS19/BFFPS19.jl, src/ReachSets/ContinuousPost/BFFPS19/reach.jl, src/ReachSets/ContinuousPost/BFFPS19/reach_blocks.jl, src/ReachSets/DiscretePost/DecomposedDiscretePost.jl, src/ReachSets/ReachSets.jl, src/solve.jl, test/Reachability/solve_hybrid.jl
Still to resolve:
* Add tests, in particular where the blocks of interest are not connected and do not start with dimension x1.
* [Check why `:overapproximation` is ignored in clustering.](https://github.com/JuliaReach/Reachability.jl/pull/641#discussion_r297127080)
Future work:
* [Add internal options as a separate field to the post operators.](https://github.com/JuliaReach/Reachability.jl/pull/641#discussion_r296843156)
=> Adding BFFPS19 CPost and Decomposed Hybrid algorithms

src/ReachSets/ContinuousPost/BFFPS19/reach.jl, src/ReachSets/ContinuousPost/BFFPS19/reach_blocks.jl, src/ReachSets/ContinuousPost/BFFPSV18/check_blocks.jl, src/ReachSets/ContinuousPost/BFFPSV18/reach.jl, src/ReachSets/ContinuousPost/BFFPSV18/reach_blocks.jl, src/ReachSets/ContinuousPost/BFFPSV18/reach_blocks_wrapping_effect.jl, src/ReachSets/ContinuousPost/TMJets/reach.jl, src/ReachSets/ReachSets.jl
Closes #632.
The problem here was that both `ProgressMeter` and `TaylorSeries` export `update!`, so we had to use `import` instead of `using` for one of those packages.
Since we use `ProgressMeter.update!` but not `TaylorSeries.update!`, I thought that we should use `import TaylorSeries` and explicitly add the functions from `TaylorSeries` that we use.
While trying this, I discovered an issue with `Requires` which I want to share here.
`TaylorSeries` also exports `normalize_taylor`, but that function only becomes visible after loading `IntervalArithmetic` via `Requires`. This can be seen as follows:
```julia
julia> using TaylorSeries
julia> normalize_taylor
ERROR: UndefVarError: normalize_taylor not defined
julia> import IntervalArithmetic
julia> normalize_taylor
normalize_taylor (generic …
```
=> #632 - Namespace conflict with TaylorSeries.update!

src/ReachSets/DiscretePost/ConcreteDiscretePost.jl
Requires:
* ~https://github.com/JuliaReach/LazySets.jl/issues/1502~
* ~https://github.com/JuliaReach/LazySets.jl/issues/1607 (waiting for new `LazySets` release)~
* ~https://github.com/JuliaReach/LazySets.jl/issues/1609 (waiting for new `LazySets` release)~
=> Remove some old workarounds from ConcreteDiscretePost

src/Utils/Utils.jl
`sparse` is used in function `matrix_conversion`.
=> Add missing import

src/ReachSets/ContinuousPost/ASB07/ASB07.jl, src/ReachSets/ContinuousPost/ASB07/init.jl, src/ReachSets/ContinuousPost/ASB07/options.jl, src/ReachSets/ContinuousPost/ASB07/post.jl, src/ReachSets/ContinuousPost/ASB07/reach.jl, src/ReachSets/ContinuousPost/GLGM06/init.jl, src/ReachSets/ContinuousPost/GLGM06/reach.jl, src/ReachSets/ReachSets.jl, src/ReachSets/discretize.jl, test/Reachability/solve_continuous.jl
Closes #639.
Requires: ~https://github.com/JuliaReach/IntervalMatrices.jl/pull/52, https://github.com/JuliaReach/LazySets.jl/pull/1681~
The unit test is the example 1 from the paper. Computing the result is quick, but plotting the zonotopes takes ages. I plotted the result for `:max_order => 3` (which is fast).
=> #639 - Reachability for LTI systems with interval matrices using zonotopes

src/ReachSets/ContinuousPost/ASB07_decomposed/ASB07_decomposed.jl, src/ReachSets/ContinuousPost/ASB07_decomposed/init.jl, src/ReachSets/ContinuousPost/ASB07_decomposed/options.jl, src/ReachSets/ContinuousPost/ASB07_decomposed/post.jl, src/ReachSets/ContinuousPost/ASB07_decomposed/reach.jl, src/ReachSets/ContinuousPost/BFFPSV18/reach_blocks.jl, src/ReachSets/ReachSets.jl, test/Reachability/solve_continuous.jl
Closes #686.
For now I called the operator `ASB07_decomposed`. We can rename it later.
I again have the problem that the set type for `ReachSolution` must be concrete. We should really get rid of this because it limits us everywhere (the workaround so far is to use `LazySet` everywhere). As suggested by @mforets, I added a workaround for now.
There is also https://github.com/JuliaReach/LazySets.jl/issues/1726 which could be incorporated later (I left a TODO in the code).
Homogeneous system:
Heterogeneous system:
=> #686 - Decomposition for ASB07

src/Utils/transformations.jl, src/solve.jl
My test below shows that there is still something missing to back-transform the result. But I think this PR still improves the state by not crashing anymore.
```julia
using SparseArrays, MathematicalSystems, Reachability
A = sparse([1, 1, 2, 2], [1, 2, 1, 2], [3., -9., 4., -3.])
B = reshape([0.0, -1.0], (2, 1))
U = Singleton([1.0])
inv = Universe(2)
model = ConstrainedLinearControlContinuousSystem(A, B, inv, ConstantInput(U))
X0 = Hyperrectangle(low=[10.0, 0.0], high=[10.2, 0.0])
problem = InitialValueProblem(model, X0)
𝑂_original = Options(:T => 20.0, :mode => "reach")
𝑂_op_original = Options(:vars => [1, 2], :partition => [[1], [2]], :δ => 0.003)
sol_original = solve(problem, 𝑂_original, op=BFFPSV18(𝑂_op_original))
𝑂_transform = merge(𝑂_original, Options(:coordinate_transformation => …
```
=> Fix crashes in Schur transformation

src/ReachSets/project_reach.jl
This fixes the first error in #707. It still crashes at a later problem.
Example from [the notebook](https://github.com/mforets/escritoire/blob/master/reachability/Projection_Errors.ipynb):
```julia
A = rand(4, 4)
S = LinearContinuousSystem(A)
X0 = rand(Hyperrectangle, dim=4)
M = rand(1, 4)  # note that this must matrix be 1D
P = InitialValueProblem(S, X0)
opts = Options(:T=>1.0, :project_reachset=>true, :projection_matrix=>M)
opts_algo = Options(:δ=>0.1, :vars=>[1, 2])
solve(P, opts, op=BFFPSV18(opts_algo))
```
=> Fix undefined projection_matrix variable

src/ReachSets/ContinuousPost/BFFPSV18/BFFPSV18.jl
This depends on https://github.com/JuliaReach/LazySets.jl/pull/1179.
To-do's:
- show example of `block_options`
- add an example for the old behavior of `lazy_X0`, to be used as: `:block_options_init => LinearMap`
- add an example passing vars and partition, which means that the algorithm computes *all blocks that contain variables in vars". see also https://github.com/JuliaReach/Reachability.jl/blob/master/src/ReachSets/ContinuousPost/BFFPSV18/BFFPSV18.jl#L298
- explain how to use some of the features wanted in [this issue](https://github.com/JuliaReach/Reachability.jl/issues/92#issuecomment-391033356)
=> WIP - Revise decompose options

src/ReachSets/ContinuousPost/ASB07_decomposed/reach.jl
This fixes a bug in `ABS07_decomposed` where the inputs were not multiplied with the matrix power.
=> Fix ABS07_decomposed with inputs

src/ReachSets/DiscretePost/LazyDiscretePost.jl, src/Utils/Utils.jl
Closes #620.
Instead of adding another option, I decided to change the option domain from `Bool` to `String` (we actually only need three possible values). Interestingly, we never used this option anywhere, so the change was simple.
=> #620 - overapproximate in LazyDiscretePost for singular map

src/ReachSets/ContinuousPost/BFFPS19/reach_blocks.jl, test/Reachability/solve_hybrid.jl
The integration of the `SparseReachSet`s was done in the wrong way.
The tests do not uncover the bug because it only triggers if some dimensions are not used.
=> Fix BFFPS19

src/ReachSets/ContinuousPost/ASB07/post.jl, src/ReachSets/ContinuousPost/ASB07/reach.jl
This is a hack to restore the algorithm `ASB07`.
=> Concretely type zonotopes in ASB07

src/ReachSets/ContinuousPost/GLGM06/post.jl, src/ReachSets/ContinuousPost/GLGM06/reach.jl, src/ReachSets/ContinuousPost/TMJets/post.jl, src/ReachSets/Flowpipe.jl
This fixes the tests again and also would allow to bump `LazySets`.
Parts of this PR are similar to #751.
=> Relax type restriction of Flowpipe

.travis.yml, Project.toml
- use artifact
- avoid redundant build
- upper-bound to Julia v1.2 (see #758)
=> Update Travis config

src/ReachSets/ContinuousPost/GLGM06/post.jl, src/ReachSets/ContinuousPost/GLGM06/reach.jl
Originally this PR should just remove the order reduction in a homogeneous `GLGM06` run.
~But then I hit a wall that the new `LazySets` v1.32 is incompatible with our flowpipes consisting of sets of fixed type (because the type may change during the analysis).~
~This PR adds a brute-force conversion for `GLGM06` but some work would be needed for other algorithms as well.~
~(The conversion after order reduction might be redundant.)~
=> Remove order reduction in GLGM06
